---
title: nogreathurry
timezone: UTC
collections:
  buildings:
    title: Buildings
    output: true
  people:
    title: People
    output: true
  abstract:
    title: Abstract
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
permalink: pretty
font: Roboto
defaults:
  - scope:
      path: ""
      type: buildings
    values:
      layout: photos
  - scope:
      path: ""
      type: people
    values:
      layout: photos
  - scope:
      path: ""
      type: abstract
    values:
      layout: photos
