---
title: nogreathurry
timezone: UTC
collections:
  abstract:
    title: abstract
    output: true
  buildings:
    title: architecture
    output: true
  people:
    title: people
    output: true
  posts:
    title: posts
    output: true
  uploads:
    title: uploads
    output: false
defaults:
- scope:
    path: ''
    type: buildings
  values:
    layout: photos
    title: ''
    image: ''
    thumbnail_image: ''
- scope:
    path: ''
    type: people
  values:
    layout: photos
    title: ''
    image: ''
    thumbnail_image: ''
- scope:
    path: ''
    type: abstract
  values:
    layout: photos
    title: ''
    image: ''
    thumbnail_image: ''
permalink: pretty
font: Roboto
email: nogreathurry@yahoo.co.uk
home_image: "/uploads/Bridges%20of%20Halifax%20thumbnail-2c4f23.jpg"
